FROM python:3.11 as builder

# Copy all the files from the folders the Dockerfile is to the container app folder streamlit cannot run from root

COPY ./app/requirements.txt requirements.txt
# Install the modules specified in the requirements.txt
RUN apt-get update && apt-get install -y \
   && apt-get install -y cmake build-essential gcc gfortran libopenblas-dev python3-h5py ca-certificates lsb-release wget libhdf5-dev\
   && pip3 install patchelf \
   && pip3 install ninja \
   && pip3 install -r requirements.txt

FROM python:3.11-slim

COPY --from=builder /root/.local /root/.local

WORKDIR /app

COPY ./app .
# The port on which a container listens for connections
EXPOSE 8501

ENV PATH=/root/.local:$PATH
# The command that run the app
CMD streamlit run Home.py --server.address 0.0.0.0 --server.port 8501