version: '3.3'
services:
  bayes_methods:
    image: redam94/bayesian_methods:0.0.1-web3
    ports:
     - 30003:8501
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.bayesapp.entrypoints: http
        traefik.http.services.bayesapp-secured.loadbalancer.server.port: '8501'
        traefik.http.middlewares.bayesapp.redirectscheme.scheme: https
        traefik.http.middlewares.bayesapp.redirectscheme.permanent: 'true'
        traefik.http.routers.bayesapp.rule: Host(`bayesian_methods.mattreda.pro`)
        traefik.constraint-label: traefik-public
        traefik.http.routers.bayesapp-secured.tls.certresolver: le
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.bayesapp-secured.entrypoints: https
        traefik.http.routers.bayesapp-secured.rule: Host(`bayesian_methods.mattreda.pro`)
      restart_policy:
        condition: on-failure
networks:
  traefik-public:
    external: true
